config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :destroy]
  resources :recipes
  devise_for :users

  root 'recipes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :recipes
	has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:destroy]
  def create
  	@comment = current_user.comments.build(comment_params)
  	@comment.save

  	redirect_to @comment.recipe
  end

  def destroy
    @recipe = @comment.recipe
    if @comment.user == current_user
    	@comment.destroy
    end 

  	redirect_to @recipe
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :recipe_id)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @comments = @recipe.comments
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :content, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onepiece</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "One Piece", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-right">
        <li>
        	<% if user_signed_in? %>
        		<%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
        	<% else %>
        		<%= link_to "로그인", new_user_session_path %>
        	<% end %>
      	</li>
      </ul>
  </div>
</nav>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<% @recipes.each do |recipe| %>
  <div class="col-xs-6 col-md-3">
    <%= link_to image_tag(recipe.image_url(:thumb)), recipe, class: "thumbnail" %>
  </div>
<% end %>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@recipe.image_url) %>
<h1><%= @recipe.title %></h1>
<p><%= @recipe.content %></p>
<p><%= @recipe.user.name %></p>
<p><%= @recipe.user.profile %></p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

<%= simple_form_for(Comment.new) do |f| %>
	<%= f.hidden_field :recipe_id, value: @recipe.id %>
	<%= f.input :content %>
	<%= f.submit "코멘트 등록" %>
<% end %>

<% @comments.each do |comment| %>
	<div class="well">
		<%= comment.user.name %>: 
		<%= comment.content %>
		<%= comment.created_at %>
		<% if comment.user == current_user %>
			<%= link_to "X", comment, method: :delete, data: { confirm: "정말 삭제하시겠습니까?" } %>
		<% end %>
	</div>
<% end %>